version: "3.7"

services:
  # Traefik reverse proxy service
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.toml"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.toml"
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allow Traefik to interact with Docker (optional)
      - "./traefik/acme.json:/etc/traefik/acme.json"  # Persistent storage for certificates
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik/dynamic_conf.toml:/etc/traefik/dynamic_conf.toml"
    labels:
      - "traefik.enable=true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # Traefik does not run web services, only serves as a reverse proxy.
