[http.routers.libraryDev]
entryPoints = ["websecure"]
rule = "Host(`library.dev.next.brausen.services`)"
service = "libraryDev-service"
middlewares = ["https-redirect"]

[http.routers.librarianDev]
entryPoints = ["websecure"]
rule = "Host(`librarian.dev.next.brausen.services`)"
service = "librarianDev-service"
middlewares = ["https-redirect"]

[http.routers.libraryDev.tls]
certResolver = "myresolver"

[http.services.libraryDev-service]
  [http.services.libraryDev-service.loadBalancer]
    [[http.services.libraryDev-service.loadBalancer.servers]]
    url = "http://host.docker.internal:3000"

[http.routers.librarianDev.tls]
certResolver = "myresolver"

[http.services.librarianDev-service]
[http.services.librarianDev-service.loadBalancer]
[[http.services.librarianDev-service.loadBalancer.servers]]
url = "http://host.docker.internal:3001"

[http.middlewares.https-redirect.redirectScheme]
scheme = "https"
permanent = true

