[providers.file]
filename = "/etc/traefik/dynamic_conf.toml"
watch = true
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[log]
  level = "DEBUG"

[certificatesResolvers.myresolver.acme]
  email = "atombrot@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"